In [17]:
# 2
import numpy as np
n = int(input())
arr = np.zeros((n,n), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

5
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [108]:
# 3
import numpy as np
n, m, r, c = (int(i) for i in input().split())
arr = np.ones((n,m), dtype=int)
arr[::r] = 0
arr[:,::c] = 0
print(arr)

6 7 2 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [18]:
# 4
import numpy as np
n, m = (int(i) for i in input().split())
arr = np.zeros((n,m), dtype=int)
arr[0]=np.arange(m)
print(arr)

3 4
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [111]:
# 5
import numpy as np
n=int(input())
arr = np.ones((n,n), dtype=int)
arr[1::2]=0
print(arr)

5
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [115]:
# 7
import numpy as np
arr = input().split()
arr = np.array(arr, dtype = int)
arr = np.where(arr==0,-1,arr)
print(arr)

3 4 0 6 5 0 3 0 4
[ 3  4 -1  6  5 -1  3 -1  4]


In [114]:
# 8
import numpy as np
arr = input().split()
arr = np.array(arr, dtype = int)
print(np.count_nonzero(arr))
# print (np.where(arr == 0))
print(int(arr.size) - np.count_nonzero(arr))

3 4 0 6 5 0 3 0 4
6
3


In [102]:
# 9
import numpy as np
n=int(input())
print(np.arange(n, -1, -1))

5
[5 4 3 2 1 0]


In [119]:
# 10
import numpy as np
n, m = (int(i) for i in input().split(" "))
arr = np.random.random((n, m))
print("min: {}".format(round(np.amin(arr), 3)))
print("max: {}".format(round(np.amax(arr), 3)))
print("average: {}".format(round(np.mean(arr), 3)))
print("disp: {}".format(round(np.std(arr), 3)))

4 5
min: 0.015
max: 0.946
average: 0.502
disp: 0.276


In [21]:
# 11
import numpy as np
n = int(input())
arr = np.zeros((n+1,n+1), dtype=int)
arr[1:-1,1:-1] = 1
print(arr)

5
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


In [47]:
# 12
import numpy as np
n=int(input())
arr = np.ones((n,n), dtype=int)
arr[0::n-1]=0
arr[::, 0::n-1]=0
print(arr)

5
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [26]:
# 13
n = 100
print(np.unravel_index(n-1, (4,5,6)))

(3, 1, 3)


In [45]:
# 15
import numpy as np
arr = np.tile([[0, 1], [1, 0]], (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [58]:
# 18
import numpy as np
n = int(input())
arr = np.random.randint(0, n, 11)
arr = np.where(arr<n/2,-arr,arr)
print(3*n/4)
arr = np.where(arr>(3*n/4),-arr,arr)
print(arr)

10
7.5
[ 0  0 -9 -1  0  7  7 -9  5 -2  0]


In [65]:
# 19
import numpy as np
n = int(input())
arr = np.random.randint(0, 99, n)
print(arr)
print(np.unique(arr).size)

30
[44 81 17  2 23 98 93 81 59 44 75 54 61 12 90 72 52 30 36 72 22  1 59 88
 39 43 59 92 72 60]
24


In [120]:
# 21
import numpy as np
n = int(input())
array = [round(i, 3) for i in np.random.random(n)]
print("created vector: {}".format(array))
print("changed vector: {}".format(np.where(array==np.amax(array), 0, array)))

5
created vector: [0.305, 0.98, 0.439, 0.413, 0.266]
changed vector: [0.305 0.    0.439 0.413 0.266]


In [124]:
import numpy as np
system = np.array([[1, 3, 5, 7, 12],[3, 5, 7, 1, 0],[5, 7, 1, 3, 4],[7, 1, 3, 5, 16]])
a1, a2, a3, a4, b = np.hsplit(system, [1, 2, 3, 4])

delta = np.concatenate([a1, a2, a3, a4], axis = 1)
delta1 = np.concatenate([b, a2, a3, a4], axis = 1)
delta2 = np.concatenate([a1, b, a3, a4], axis = 1)
delta3 = np.concatenate([a1, a2, b, a4], axis = 1)
delta4 = np.concatenate([a1, a2, a3, b], axis = 1)
print(system)
print(delta)
print(delta1)
print(delta2)
print(delta3)
print(delta4)

x1 = np.linalg.det(delta1) / np.linalg.det(delta)
x2 = np.linalg.det(delta2) / np.linalg.det(delta)
x3 = np.linalg.det(delta3) / np.linalg.det(delta)
x4 = np.linalg.det(delta4) / np.linalg.det(delta)

print("x1 = {}\nx2 = {}\nx3 = {}\nx4 = {}\n".format(x1, x2, x3, x4))
print("matrix mult: ")
print(system[::, :4:].dot([x1, x2, x3, x4]))

print("numpy.lanalg.solve(): ")
print(np.linalg.solve(system[::, :4:], system[::, 4]))
print(system[::, :4:].dot(np.linalg.solve(system[::, :4:], system[::, 4])))

[[ 1  3  5  7 12]
 [ 3  5  7  1  0]
 [ 5  7  1  3  4]
 [ 7  1  3  5 16]]
[[1 3 5 7]
 [3 5 7 1]
 [5 7 1 3]
 [7 1 3 5]]
[[12  3  5  7]
 [ 0  5  7  1]
 [ 4  7  1  3]
 [16  1  3  5]]
[[ 1 12  5  7]
 [ 3  0  7  1]
 [ 5  4  1  3]
 [ 7 16  3  5]]
[[ 1  3 12  7]
 [ 3  5  0  1]
 [ 5  7  4  3]
 [ 7  1 16  5]]
[[ 1  3  5 12]
 [ 3  5  7  0]
 [ 5  7  1  4]
 [ 7  1  3 16]]
x1 = 1.0000000000000009
x2 = -1.0000000000000009
x3 = -7.853566282149544e-17
x4 = 2.0

matrix mult: 
[ 1.20000000e+01 -2.22044605e-15  4.00000000e+00  1.60000000e+01]
numpy.lanalg.solve(): 
[ 1.00000000e+00 -1.00000000e+00 -5.24271984e-17  2.00000000e+00]
[12.  0.  4. 16.]


In [133]:
import numpy as np
A = np.array([[5,2,0], [10,4,1], [7,3,2]])
B = np.array([[3,6,-1], [-1,-2,0], [2,1,3]])

print(A)
print()
print(B)
print()
print("(A-B²)(2A+B)\n")

print("\nA-B²\n")
print(A, end="\n - \n")
print(B.dot(B), end = "\n = \n")
print(A - B.dot(B))

print("\n2A+B\n")
print(2*A, end="\n + \n")
print(B, end = "\n = \n")
print(2*A + B)

print("\n(A-B²)(2A+B)\n")
print(A - B.dot(B), end = "\n-\n")
print(2*A+B, end = "\n=\n")
print((A - B.dot(B)).dot(2*A + B))

[[ 5  2  0]
 [10  4  1]
 [ 7  3  2]]

[[ 3  6 -1]
 [-1 -2  0]
 [ 2  1  3]]

(A-B²)(2A+B)


A-B²

[[ 5  2  0]
 [10  4  1]
 [ 7  3  2]]
 - 
[[ 1  5 -6]
 [-1 -2  1]
 [11 13  7]]
 = 
[[  4  -3   6]
 [ 11   6   0]
 [ -4 -10  -5]]

2A+B

[[10  4  0]
 [20  8  2]
 [14  6  4]]
 + 
[[ 3  6 -1]
 [-1 -2  0]
 [ 2  1  3]]
 = 
[[13 10 -1]
 [19  6  2]
 [16  7  7]]

(A-B²)(2A+B)

[[  4  -3   6]
 [ 11   6   0]
 [ -4 -10  -5]]
-
[[13 10 -1]
 [19  6  2]
 [16  7  7]]
=
[[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]


In [134]:
import numpy as np
A = np.array([[2,3,1],[4,-1,0],[0,1,2]])
B = np.array([[9,8,7],[2,7,3],[4,3,5]])

print("А")
print(A)
print("В")
print(B)
print("inv(A) * B = ")
result = A.dot(np.linalg.inv(B))
print(result)
print("matrix mult: ")
print(result.dot(A))
print("numpy.linalg.solve(): ")
print(np.linalg.solve(result, A))

А
[[ 2  3  1]
 [ 4 -1  0]
 [ 0  1  2]]
В
[[9 8 7]
 [2 7 3]
 [4 3 5]]
inv(A) * B = 
[[ 0.375    0.1875  -0.4375 ]
 [ 1.0625  -0.96875 -0.90625]
 [-0.4375   0.28125  0.84375]]
matrix mult: 
[[ 1.5   0.5  -0.5 ]
 [-1.75  3.25 -0.75]
 [ 0.25 -0.75  1.25]]
numpy.linalg.solve(): 
[[9. 8. 7.]
 [2. 7. 3.]
 [4. 3. 5.]]
